# Generated by Django 3.1.2 on 2020-12-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_blogcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterSuccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('successScore', models.TextField()),
            ],
        ),
    ]
