# Generated by Django 3.1.2 on 2020-12-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_countersuccess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CounterSuccess',
        ),
    ]
