# Generated by Django 3.1.2 on 2020-12-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_counter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counter',
        ),
    ]
