# Generated by Django 3.1.2 on 2020-12-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.TextField()),
            ],
        ),
    ]
