# Generated by Django 3.1.2 on 2021-01-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_delete_highandlowscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighAndLowScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=10)),
                ('tryCount', models.CharField(max_length=50)),
            ],
        ),
    ]
