# Generated by Django 3.1.2 on 2021-01-06 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_highandlowscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counterscore',
            old_name='score',
            new_name='name',
        ),
    ]
