# Generated by Django 3.1.2 on 2021-01-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210106_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='comment',
            new_name='content',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='postID',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='userName',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
